// @ts-check

import { defineConfig, globalIgnores } from 'eslint/config'
import { tanstackConfig } from '@tanstack/eslint-config'
import convexPlugin from '@convex-dev/eslint-plugin'

export default defineConfig([
  ...tanstackConfig,
  ...convexPlugin.configs.recommended,
  {
    rules: {
      'import/no-cycle': 'off',
      'import/order': 'off',
      'sort-imports': 'off',
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/require-await': 'off',
    },
  },
  {
    // Generated by `shadcn add`; keep them diff-free against the registry.
    files: ['src/components/ui/**', 'src/lib/utils.ts'],
    rules: { 'import/consistent-type-specifier-style': 'off' },
  },
  globalIgnores([
    'convex/_generated',
    'src/routeTree.gen.ts',
    '.output',
    '.nitro',
    '.tanstack',
    '.vercel',
    '.llms-fetch-mcp',
    'scratch',
    '.claude/scripts',
    'eslint.config.js',
    'prettier.config.js',
  ]),
])
