// Invite and session tokens. The plaintext exists exactly once — in the URL or
// cookie handed to the guest — and the database only ever sees its hash.

export function newToken(): string {
  const bytes = new Uint8Array(32)
  crypto.getRandomValues(bytes)
  let binary = ''
  for (const byte of bytes) binary += String.fromCharCode(byte)
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

export async function hashToken(token: string): Promise<string> {
  const digest = await crypto.subtle.digest(
    'SHA-256',
    new TextEncoder().encode(token),
  )
  return Array.from(new Uint8Array(digest), (byte) =>
    byte.toString(16).padStart(2, '0'),
  ).join('')
}

// Session tokens are generated by the browser (see src/lib/session.ts); refuse
// anything shorter than our own 32-byte tokens.
export const MIN_SESSION_TOKEN_LENGTH = 32
