/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as GuestIndexRouteImport } from './routes/_guest/index'
import { Route as GuestActivitiesRouteImport } from './routes/_guest/activities'
import { Route as GuestAdminRouteImport } from './routes/_guest/admin'
import { Route as GuestAvailabilityRouteImport } from './routes/_guest/availability'
import { Route as GuestProposeRouteImport } from './routes/_guest/propose'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as GuestAdminIndexRouteImport } from './routes/_guest/admin/index'
import { Route as GuestAdminActivitiesRouteImport } from './routes/_guest/admin/activities'
import { Route as GuestAdminExportRouteImport } from './routes/_guest/admin/export'
import { Route as GuestAdminGuestsRouteImport } from './routes/_guest/admin/guests'
import { Route as GuestAdminInvitesRouteImport } from './routes/_guest/admin/invites'
import { Route as GuestAdminScheduleRouteImport } from './routes/_guest/admin/schedule'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestActivitiesRoute = GuestActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAdminRoute = GuestAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAvailabilityRoute = GuestAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => GuestRoute,
} as any)
const GuestProposeRoute = GuestProposeRouteImport.update({
  id: '/propose',
  path: '/propose',
  getParentRoute: () => GuestRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestAdminIndexRoute = GuestAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestAdminRoute,
} as any)
const GuestAdminActivitiesRoute = GuestAdminActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => GuestAdminRoute,
} as any)
const GuestAdminExportRoute = GuestAdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => GuestAdminRoute,
} as any)
const GuestAdminGuestsRoute = GuestAdminGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => GuestAdminRoute,
} as any)
const GuestAdminInvitesRoute = GuestAdminInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => GuestAdminRoute,
} as any)
const GuestAdminScheduleRoute = GuestAdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => GuestAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GuestIndexRoute
  '/welcome': typeof WelcomeRoute
  '/activities': typeof GuestActivitiesRoute
  '/admin': typeof GuestAdminRouteWithChildren
  '/availability': typeof GuestAvailabilityRoute
  '/propose': typeof GuestProposeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/activities': typeof GuestAdminActivitiesRoute
  '/admin/export': typeof GuestAdminExportRoute
  '/admin/guests': typeof GuestAdminGuestsRoute
  '/admin/invites': typeof GuestAdminInvitesRoute
  '/admin/schedule': typeof GuestAdminScheduleRoute
  '/admin/': typeof GuestAdminIndexRoute
}
export interface FileRoutesByTo {
  '/welcome': typeof WelcomeRoute
  '/activities': typeof GuestActivitiesRoute
  '/availability': typeof GuestAvailabilityRoute
  '/propose': typeof GuestProposeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof GuestIndexRoute
  '/admin/activities': typeof GuestAdminActivitiesRoute
  '/admin/export': typeof GuestAdminExportRoute
  '/admin/guests': typeof GuestAdminGuestsRoute
  '/admin/invites': typeof GuestAdminInvitesRoute
  '/admin/schedule': typeof GuestAdminScheduleRoute
  '/admin': typeof GuestAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_guest': typeof GuestRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/_guest/activities': typeof GuestActivitiesRoute
  '/_guest/admin': typeof GuestAdminRouteWithChildren
  '/_guest/availability': typeof GuestAvailabilityRoute
  '/_guest/propose': typeof GuestProposeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_guest/': typeof GuestIndexRoute
  '/_guest/admin/activities': typeof GuestAdminActivitiesRoute
  '/_guest/admin/export': typeof GuestAdminExportRoute
  '/_guest/admin/guests': typeof GuestAdminGuestsRoute
  '/_guest/admin/invites': typeof GuestAdminInvitesRoute
  '/_guest/admin/schedule': typeof GuestAdminScheduleRoute
  '/_guest/admin/': typeof GuestAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/activities'
    | '/admin'
    | '/availability'
    | '/propose'
    | '/invite/$token'
    | '/admin/activities'
    | '/admin/export'
    | '/admin/guests'
    | '/admin/invites'
    | '/admin/schedule'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/welcome'
    | '/activities'
    | '/availability'
    | '/propose'
    | '/invite/$token'
    | '/'
    | '/admin/activities'
    | '/admin/export'
    | '/admin/guests'
    | '/admin/invites'
    | '/admin/schedule'
    | '/admin'
  id:
    | '__root__'
    | '/_guest'
    | '/welcome'
    | '/_guest/activities'
    | '/_guest/admin'
    | '/_guest/availability'
    | '/_guest/propose'
    | '/invite/$token'
    | '/_guest/'
    | '/_guest/admin/activities'
    | '/_guest/admin/export'
    | '/_guest/admin/guests'
    | '/_guest/admin/invites'
    | '/_guest/admin/schedule'
    | '/_guest/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GuestRoute: typeof GuestRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/activities': {
      id: '/_guest/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof GuestActivitiesRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/admin': {
      id: '/_guest/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof GuestAdminRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/availability': {
      id: '/_guest/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof GuestAvailabilityRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/propose': {
      id: '/_guest/propose'
      path: '/propose'
      fullPath: '/propose'
      preLoaderRoute: typeof GuestProposeRouteImport
      parentRoute: typeof GuestRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/admin/': {
      id: '/_guest/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof GuestAdminIndexRouteImport
      parentRoute: typeof GuestAdminRoute
    }
    '/_guest/admin/activities': {
      id: '/_guest/admin/activities'
      path: '/activities'
      fullPath: '/admin/activities'
      preLoaderRoute: typeof GuestAdminActivitiesRouteImport
      parentRoute: typeof GuestAdminRoute
    }
    '/_guest/admin/export': {
      id: '/_guest/admin/export'
      path: '/export'
      fullPath: '/admin/export'
      preLoaderRoute: typeof GuestAdminExportRouteImport
      parentRoute: typeof GuestAdminRoute
    }
    '/_guest/admin/guests': {
      id: '/_guest/admin/guests'
      path: '/guests'
      fullPath: '/admin/guests'
      preLoaderRoute: typeof GuestAdminGuestsRouteImport
      parentRoute: typeof GuestAdminRoute
    }
    '/_guest/admin/invites': {
      id: '/_guest/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof GuestAdminInvitesRouteImport
      parentRoute: typeof GuestAdminRoute
    }
    '/_guest/admin/schedule': {
      id: '/_guest/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof GuestAdminScheduleRouteImport
      parentRoute: typeof GuestAdminRoute
    }
  }
}

interface GuestAdminRouteChildren {
  GuestAdminActivitiesRoute: typeof GuestAdminActivitiesRoute
  GuestAdminExportRoute: typeof GuestAdminExportRoute
  GuestAdminGuestsRoute: typeof GuestAdminGuestsRoute
  GuestAdminInvitesRoute: typeof GuestAdminInvitesRoute
  GuestAdminScheduleRoute: typeof GuestAdminScheduleRoute
  GuestAdminIndexRoute: typeof GuestAdminIndexRoute
}

const GuestAdminRouteChildren: GuestAdminRouteChildren = {
  GuestAdminActivitiesRoute: GuestAdminActivitiesRoute,
  GuestAdminExportRoute: GuestAdminExportRoute,
  GuestAdminGuestsRoute: GuestAdminGuestsRoute,
  GuestAdminInvitesRoute: GuestAdminInvitesRoute,
  GuestAdminScheduleRoute: GuestAdminScheduleRoute,
  GuestAdminIndexRoute: GuestAdminIndexRoute,
}

const GuestAdminRouteWithChildren = GuestAdminRoute._addFileChildren(
  GuestAdminRouteChildren,
)

interface GuestRouteChildren {
  GuestActivitiesRoute: typeof GuestActivitiesRoute
  GuestAdminRoute: typeof GuestAdminRouteWithChildren
  GuestAvailabilityRoute: typeof GuestAvailabilityRoute
  GuestProposeRoute: typeof GuestProposeRoute
  GuestIndexRoute: typeof GuestIndexRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestActivitiesRoute: GuestActivitiesRoute,
  GuestAdminRoute: GuestAdminRouteWithChildren,
  GuestAvailabilityRoute: GuestAvailabilityRoute,
  GuestProposeRoute: GuestProposeRoute,
  GuestIndexRoute: GuestIndexRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GuestRoute: GuestRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
