/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as GuestIndexRouteImport } from './routes/_guest/index'
import { Route as GuestAdminRouteImport } from './routes/_guest/admin'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestIndexRoute = GuestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuestRoute,
} as any)
const GuestAdminRoute = GuestAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => GuestRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GuestIndexRoute
  '/welcome': typeof WelcomeRoute
  '/admin': typeof GuestAdminRoute
  '/invite/$token': typeof InviteTokenRoute
}
export interface FileRoutesByTo {
  '/welcome': typeof WelcomeRoute
  '/admin': typeof GuestAdminRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof GuestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_guest': typeof GuestRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/_guest/admin': typeof GuestAdminRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_guest/': typeof GuestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/welcome' | '/admin' | '/invite/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/welcome' | '/admin' | '/invite/$token' | '/'
  id:
    | '__root__'
    | '/_guest'
    | '/welcome'
    | '/_guest/admin'
    | '/invite/$token'
    | '/_guest/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GuestRoute: typeof GuestRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/': {
      id: '/_guest/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GuestIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/admin': {
      id: '/_guest/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof GuestAdminRouteImport
      parentRoute: typeof GuestRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuestRouteChildren {
  GuestAdminRoute: typeof GuestAdminRoute
  GuestIndexRoute: typeof GuestIndexRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestAdminRoute: GuestAdminRoute,
  GuestIndexRoute: GuestIndexRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GuestRoute: GuestRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
